# Get all books
GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

###

# Create a book
POST  http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
   "title": "Harry Potter"
}

###

# Update a book
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
   "title": "Dark Tower"
}

###

# Delete a book
DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json