const menu = [
  {
    id: 1,
    title: "Karataş Plajı",
    category: "adana",
    price: 100,
    img: "https://seyyahdefteri.com/wp-content/uploads/2019/07/Akmaz-Plaji-ve-Karatas-Plaji.jpg",
    desc: `Ülkemizdeki en uzun kumsallardan birisidir. Etrafı temizlik anlamında ideal olmasa da kesintisiz 6 kilometre uzunluğu ile ziyaretçilerini ağırlamaktadır. ". `,
  },
  {
    id: 2,
    title: "Adana Yumurtalık Plajı",
    category: "adana",
    price: 100,
    img: "https://cdn.otelleri.net/landing/adana/gezi-rehberi/karatas-plaji-2514-54.jpg",
    desc: `Yumurtalık, Adana ilinin bir ilçesidir. Eski adı Ayas olup, Türkçeleştirmek adına ismi Yumurtalık'a çevrilmiştir.`,
  },
  {
    id: 3,
    title: "İncirlik Plajı",
    category: "adana",
    price: 100,
    img: "https://cdn.otelleri.net/landing/adana/gezi-rehberi/incirli-plaji-2514-d6.jpg",
    desc: `Adana sahil şeridinin en batısında yer alan ve Ceyhan Belediyesi sınırları içindeki Kurtpınar Beldesi sınırları içerisinde bulunmaktadır.`,
  },
  {
    id: 4,
    title: "Tarsusta Kanal",
    category: "tarsus",
    price: 10,
    img: "https://img.piri.net/resim/imagecrop/2022/06/01/11/30/resized_a08e8-56311f39456843701.jpg",
    desc: `Tarsusta da herhangi bir kanalda serinliyebilirsiniz mükemmel bir seyir zevki şehir sankinleri için.`,
  },
  {
    id: 5,
    title: "Tisan Yarımadası, Yeşilovacık",
    category: "mersin",
    price: 150,
    img: "https://www.bizevdeyokuz.com/wp-content/uploads/tisan-yarimadasi-mersin.jpg",
    desc: `Tisan, Mersin’in en popüler plajlarından biri. Bir sitenin içinden geçerek giriliyorsa da halka açık.`,
  },
  {
    id: 6,
    title: "Boğsak Koyu, Taşucu",
    category: "mersin",
    price: 150,
    img: "https://www.bizevdeyokuz.com/wp-content/uploads/Bogsak_Koyu_Mersin.jpg",
    desc: `Mersin’in Caretta Carettaların uğradığı, mavi bayraklı koylarından biri. Denizi dalgasız, sığ ve temiz. Etrafta salaş işletmeler ve kamp alanları var. Hafta sonu kalabalık olabiliyor. `,
  },
  {
    id: 7,
    title: "Yapraklı Koy",
    category: "mersin",
    price: 150,
    img: "https://www.bizevdeyokuz.com/wp-content/uploads/Yaprakli-koy-mersin.jpg",
    desc: `Turistleri bırakın Mersinlilerin bile Mersin’de denize girmek için en çok tercih ettikleri koy. Turkuaz renkli, kumsal, etrafı kayalarla çevrili adeta doğal bir havuz. `,
  },
  {
    id: 8,
    title: "Soğuksu Plajı",
    category: "mersin",
    price: 150,
    img: "https://www.bizevdeyokuz.com/wp-content/uploads/soguksu-plaji-mersin.jpg",
    desc: `İncekum’dan Antalya yönüne doğru devam edince Soğuksu Koyu karşınıza çıkıyor. Dağdan gelen su Soğuksu Çayı ile denizle birleştiğinden deniz sıcaklığı daha düşük.`,
  },
];
export default menu;
